### ISSUE TITLE
Feature request: Tensor product of a list of path algebras

### ISSUE THREAD

**Issue by heiderich** [oysteins/QPA2#14]
It would be nice if one could construct the tensor product of a finite list of path algebras and if it would be possible to map elements of iteratively constructed tensor products of path algebras (and tensor products thereof) to such a tensor product.

For instance in a situation such as

```
LoadPackage("QPA");
LoadPackage("RingsForHomalg");
q := RightQuiver( "q(1)[t:1->1]" );
Q := HomalgFieldOfRationals( );
Qq := PathAlgebra( Q, q );
Qqq := TensorProductOfAlgebras(Qq,Qq);
Qqq_q := TensorProductOfAlgebras(Qqq,Qq);
Qq_qq := TensorProductOfAlgebras(Qq,Qqq);
```

it would be nice if one could construct the 3-fold tensor product directly, maybe as follows:

`Qqqq := TensorProductOfAlgebras([Qq,Qq,Qq]);`

In addition, it would be nice if one could map elements of `Qqq_q` and of `Qq_qq` to `Qqqq`.

**Comment by oysteins** [comment]
I have now implemented a new version of `TensorProductOfAlgebras` which takes a list of algebras as argument, and added a new attribute `IsomorphismToFlatTensorProduct` which takes an iterated tensor product as argument and produces the isomorphism to the flat tensor product.

I have only tested these on one small example.  Please let me know if they do not work as expected in your cases.

**Comment by heiderich** [comment]
Thank you very much!
