### ISSUE TITLE
BasisPaths for specified vertices

### ISSUE THREAD

**Issue by sebastianpos** [oysteins/QPA2#21]
It would be nice to have a variant of the command
`BasisPaths`
that takes as an input two vertices `v1, v2` and a quiver algebra `A` and outputs a basis for the paths from `v1` to `v2` in `A` (provided `A` is of finite dimension). This is useful when you regard `A` as a category whose objects are given by the vertices. Then this command would yield a k-basis of the corresponding Hom-space between two vertices.

**Comment by oysteins** [comment]
This can be done by calling:
```
Filtered( BasisPaths( CanonicalBasis( A ) ),
          p -> Source( p ) = v1 and Target( p ) = v2 )
```
I can of course add an operation which does precisely this:
```
DeclareOperation( "BasisPathsBetweenVertices", [ IsQuiverAlgebra, IsVertex, IsVertex ] );
InstallMethod( BasisPathsBetweenVertices, [ IsQuiverAlgebra, IsVertex, IsVertex ],
function( A, v1, v2 )
  return Filtered( BasisPaths( CanonicalBasis( A ) ),
                   p -> Source( p ) = v1 and Target( p ) = v2 )
end );
```
Does this seem like a reasonable solution?

**Comment by sebastianpos** [comment]
Yes, I would like that very much.
Thank you :-)

**Comment by sebastianpos** [comment]
I actually have a follow-up question related to the original one:
when I want to express a given element in a quiver algebra as a linear combination of the basis paths in the canoncial basis, is it correct to use the (undocumented) `CoefficientsOfPaths` command for this task, and if yes, what is the difference to `CoefficientsOfPathsSorted?`

**Comment by oysteins** [comment]
Regarding the question about `CoefficientsOfPaths` and `CoefficientsOfPathsSorted`: The answer is yes, and they were not intended to be undocumented.  I added documentation for these functions in commit f408ca5a.

The difference between the two functions is that the `...Sorted` version assumes the paths to be in increasing order (and happily gives the wrong result if they are not), which makes it slightly more efficient (this small difference in efficiency is probably not noticeable between all the inefficiency elsewhere in QPA).

The functions `BasisPaths` and `BasisPathsBetweenVertices` do return a list of paths in increasing order (this should probably be made clear in the documentation), so when your list of paths comes from one of these, it is safe to use `CoefficientsOfPathSorted`.

**Comment by oysteins** [comment]
When I wrote the suggestion for an implementation of the function `BasisPathsBetweenVertices` above, I forgot the semicolon at the end of the `return` statement.  Then I copied that code directly into the QPA source, commited, and closed the issue -- without testing the new function or even trying to load QPA in GAP.  I'm reopening the issue now, and then I'll fix the code so that it actually works.

**Comment by sebastianpos** [comment]
Thanks a lot.
