### ISSUE TITLE
LinearCombination for QPAVectorSpaces doesn't always gives correct answers!

### ISSUE THREAD

**Issue by kamalsaleh** [oysteins/QPA2#3]
Hallo, 

Here is an example:
V := RowVectorSpace( Rationals, 2 );
#! <vector space of dimension 2 over Rationals>
LinearCombination( CanonicalBasis( V ), [ 1, 1 ] );
#! <row vector [ 1, 1 ]>
LinearCombination( CanonicalBasis( V ), [ 1/3, 1/2 ] );
#! <row vector [ 1, 1 ]>

This causes errors when computing kernel embedding of some representation morphisms. 

Q := RightQuiver("Q1(3)[a:1->2,b:2->3]" );
#! Q1(3)[a:1->2,b:2->3]
A := PathAlgebra( Rationals, Q );
#! Rationals * Q1
m12 := MatrixByRows( Rationals, [ [ 2, 4 ] ] );
#! <1x2 matrix over Rationals>
m23 := MatrixByRows( Rationals, [ [ 3, 4, 5 ], [ 1, 2, 3 ] ] );
#! <2x3 matrix over Rationals>
r1 := QuiverRepresentation( A, [ 1, 2, 3 ], [ m12, m23 ] );
#! <1,2,3>
r2 := QuiverRepresentation( A, [ 1, 1, 1 ], [ MatrixByRows( Rationals, [ [ 2 ] ] ), MatrixByRows( Rationals, [ [ 4 ] ] ) ] );
#! <1,1,1>
f1 := MatrixByRows( Rationals, [ [ 5 ] ] );;
f2 := MatrixByRows( Rationals, [ [ 3 ], [ 1 ] ] );;
f3 := MatrixByRows( Rationals, [ [ 4 ], [ 0 ], [ 0 ] ] );;
f := QuiverRepresentationHomomorphism( r1, r2, [ f1, f2, f3 ] );
#! <(1,2,3)->(1,1,1)>
KernelEmbedding( f );
Error, Does not commute with maps for arrow <arrow b in Q1> called from...

The direct reasone for this error is line 60 in file vectorspace.gi where the positions of the arguments  
coeffs, CanonicalBasis( V ) are reversed. After correcting the positions one still gets a matrix ( kernel functorial ) but that doesn't make the diagram commutative because of the above mentioned problem of "LinearCombination".

Edite: 
I guess I found the origin of the mistake, it is in the return part of the method 
"InstallMethod( \*, [ IsMultiplicativeElement, IsQPAVector ], ... )". The last argument should be a*v!.entries.
 
Best wishes

**Comment by oysteins** [comment]
Thank you very much for reporting this.

In commit 7acb352b267ff8cfdb1d6a36ace3b73709da4b49, I have corrected these two mistakes.
